### ISSUE TITLE
mergedOptions not updating when options changes

### ISSUE THREAD

**Issue by MikaelJohnAndersson** [NetCZ/vue-pikaday#162]
I'm trying to dynamically change minDate and maxDate by passing an updated options object. When inspecting the component in Vue devtools, the options prop is updated accordingly while mergedOptions still contains the old values and the calendar still displays restrictions for previous min/max date values.

I would greatly appreciate if the options were reactive, It's been a super sleek and easy to use solution for cross-browser date picking so far!

**Comment by NetCZ** [comment]
Implemented in [v1.3.0](https://github.com/NetCZ/vue-pikaday/releases/tag/v1.3.0)
